### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by m-nathani** [guilhermepontes/simple-react-redux-boilerplate#1]
Getting unexpected token import on `npm start`

`
> simple-react-redux-boilerplate@0.0.1 start /home/murtaza/training/react-giphy
> if-env NODE_ENV=production && npm run start:prod || npm run start:dev

> simple-react-redux-boilerplate@0.0.1 start:dev /home/murtaza/training/react-giphy
> webpack-dev-server --inline --hot --content-base public/

/home/murtaza/training/react-giphy/webpack.config.babel.js:1
(function (exports, require, module, __filename, __dirname) { import path from 'path';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at loader (/home/murtaza/training/react-giphy/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/murtaza/training/react-giphy/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simple-react-redux-boilerplate@0.0.1 start:dev: `webpack-dev-server --inline --hot --content-base public/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the simple-react-redux-boilerplate@0.0.1 start:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/murtaza/.npm/_logs/2019-01-31T16_20_12_146Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simple-react-redux-boilerplate@0.0.1 start: `if-env NODE_ENV=production && npm run start:prod || npm run start:dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the simple-react-redux-boilerplate@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/murtaza/.npm/_logs/2019-01-31T16_20_12_267Z-debug.log
`

**Comment by guilhermepontes** [comment]
Sorry, this project is not being updated anymore. I recommend you to simply use `create-react-app` instead.
